### ISSUE TITLE
Lead values and number of treated units

### ISSUE THREAD

**Issue by hijjang13** [insongkim/PanelMatch#65]
Hi Panelmatch team,

I recently noticed that when I changed the lead (L) value, the number of treated units changes.

For example, when I changed the L from 0 to 0:4, the number of treated units decreased from 51 to 37.

I noticed that this is because the function drops treated groups with treatment period less than 3. For example, (0,0,0,1,1,1,0) is dropped because it has no treatment at F=4 (t+4).

I think that, if so, the contemporaneous effect, such as when F=0 (t), will not be based on all available observations. Even (0,0,0,1,1,1,0) case can be used to calculate the effect until F=3. So, my guess is that even if I choose L = 0:4, ATT for F<4 should be calculated from data including such cases. Or, do I miss something?

Thanks,
Jay

**Comment by adamrauh** [comment]
Hi Jay,

Your understanding sounds correct, actually. The code works this way (keeping only matched sets that have data for the entire lead window) so that the sets used to calculate each estimate (t+0, t+1, etc. ) are all the same, to help with interpretation. In other words, this behavior ensures that the set of matched sets used for each estimation calculation is identical across each of the specified periods. 

If you would prefer, you could specify each lead period separately (`lead = 0` vs. `lead = 0:4`), which will maximize the amount of data that can be used.

We'll update the documentation to be more clear about this, so thank you for raising it.

Adam

**Comment by hijjang13** [comment]
@adamrauh Thanks for the clarification!
